<?php

declare(strict_types=1);

namespace App\Services\Sites;

use App\Models\Site;
use Symfony\Component\Yaml\Yaml;

/**
 * Renders a Site's runtime configuration as a dply.yaml manifest
 * string. Mirrors the keys understood by DplyManifestParser:
 * runtime, version, build, release (= [start_command]), processes.
 *
 * Deliberately omits deployment-shape fields (env vars, domains,
 * server, database) — those stay in the dashboard per
 * DplyManifest's docblock contract. The exported manifest is
 * "code-shape only", suitable for committing to the repo.
 *
 * Empty fields are omitted from the output to keep the file
 * minimal — a site with only a runtime pinned exports a one-line
 * `runtime: node` and nothing else.
 */
class SiteManifestExporter
{
    public function render(Site $site): string
    {
        $manifest = [];

        $runtime = $site->runtimeKey();
        if ($runtime !== null && $runtime !== '') {
            $manifest['runtime'] = $runtime;
        }

        $version = $site->runtimeVersion();
        if ($version !== null && $version !== '') {
            $manifest['version'] = $version;
        }

        if (! empty($site->build_command)) {
            $manifest['build'] = [(string) $site->build_command];
        }

        if (! empty($site->start_command)) {
            $manifest['release'] = [(string) $site->start_command];
        }

        $processes = $site->processes()
            ->orderBy('type')
            ->orderBy('name')
            ->get(['name', 'command', 'scale']);
        if ($processes->isNotEmpty()) {
            $manifest['processes'] = [];
            foreach ($processes as $p) {
                $entry = ['command' => (string) ($p->command ?? '')];
                if ((int) $p->scale !== 1) {
                    $entry['scale'] = (int) $p->scale;
                }
                $manifest['processes'][$p->name] = $entry;
            }
        }

        if ($manifest === []) {
            return "# Site has no exportable runtime configuration yet.\n";
        }

        $header = sprintf(
            "# Generated by dply:site:export-manifest from site %s (%s).\n# Edit and commit to your repo to pin this configuration.\n\n",
            $site->name,
            $site->id,
        );

        return $header.Yaml::dump($manifest, inline: 4, indent: 2);
    }
}
