<?php

declare(strict_types=1);

namespace App\Support\Edge;

/**
 * Writes a Wrangler config file from Laravel edge config for production deploys.
 */
class EdgeWranglerConfigGenerator
{
    public function outputPath(): string
    {
        return base_path('packages/edge-worker/wrangler.generated.toml');
    }

    public function write(?EdgeDeliveryContext $context = null): string
    {
        $context ??= EdgeDeliveryContext::platform();

        if ($context->r2Bucket === '' || $context->kvNamespaceId === '') {
            throw new \RuntimeException('R2 bucket and KV namespace id are required to generate Wrangler config.');
        }

        $lines = [
            '# Generated by dply — do not edit. Run: php artisan edge:worker:deploy',
            'name = '.json_encode($context->workerScriptName, JSON_UNESCAPED_SLASHES),
            'main = "src/index.ts"',
            'compatibility_date = "2024-11-01"',
            '',
            '[vars]',
            'ENVIRONMENT = "production"',
            '',
            '[[r2_buckets]]',
            'binding = "ARTIFACTS"',
            'bucket_name = '.json_encode($context->r2Bucket, JSON_UNESCAPED_SLASHES),
            '',
            '[[kv_namespaces]]',
            'binding = "HOST_MAP"',
            'id = '.json_encode($context->kvNamespaceId, JSON_UNESCAPED_SLASHES),
        ];

        if ($context->workerRoutes !== [] && $context->workerZoneName !== '') {
            $lines[] = '';
            foreach ($context->workerRoutes as $pattern) {
                $lines[] = '[[routes]]';
                $lines[] = 'pattern = '.json_encode($pattern, JSON_UNESCAPED_SLASHES);
                $lines[] = 'zone_name = '.json_encode($context->workerZoneName, JSON_UNESCAPED_SLASHES);
                $lines[] = '';
            }
        }

        $contents = rtrim(implode("\n", $lines))."\n";
        file_put_contents($this->outputPath(), $contents);

        return $this->outputPath();
    }
}
