<?php

use App\Support\SiteSettingsSidebar;

/**
 * Slug maps for VM server workspace and BYO site workspace contextual docs.
 * Keys align with {@see config/server_workspace.php} nav keys and
 * {@see SiteSettingsSidebar} section ids.
 */

return [
    'server_workspace_slugs' => [
        'overview' => 'server-overview',
        'sites' => 'server-sites',
        'run' => 'server-run',
        'console' => 'server-console',
        'health' => 'server-health',
        'shared-host' => 'server-shared-host',
        'patches' => 'server-patches',
        'hygiene' => 'server-hygiene',
        'cert-inventory' => 'server-certificates',
        'security-digest' => 'server-security',
        'blueprint' => 'server-blueprint',
        'maintenance' => 'server-maintenance',
        'deploy-policy' => 'server-deploy-windows',
        'insights' => 'server-insights',
        'monitor' => 'server-metrics',
        'activity' => 'server-activity',
        'caches' => 'server-caches',
        'docker' => 'server-docker',
        'databases' => 'server-databases',
        'php' => 'server-php',
        'services' => 'server-services',
        'webserver' => 'server-webserver',
        'edge-proxy' => 'server-edge-proxy',
        'configuration' => 'server-configuration',
        'cron' => 'server-cron',
        'schedule' => 'server-schedule',
        'daemons' => 'server-daemons',
        'backups' => 'server-backups',
        'firewall' => 'server-firewall',
        'ssh' => 'server-ssh-keys',
        'ssh-access' => 'server-ssh-access',
        'system-users' => 'server-system-users',
        'logs' => 'server-logs',
        'files' => 'server-files',
        'manage' => 'server-manage',
        'settings' => 'server-settings',
        'cluster' => 'server-cluster',
        'errors' => 'server-errors',
        'networking' => 'server-networking',
        'load-balancers' => 'server-load-balancers',
        'worker-pool' => 'server-worker-pool',
        'snapshots' => 'server-snapshots',
    ],

    'site_section_slugs' => [
        'general' => 'vm-site-overview',
        'settings' => 'vm-site-settings',
        'routing' => 'vm-site-routing',
        'dns' => 'vm-site-dns',
        'certificates' => 'vm-site-certificates',
        'deploy' => 'vm-site-deploy',
        'pipeline' => 'vm-site-deploy',
        'repository' => 'vm-site-repository',
        'runtime' => 'vm-site-runtime',
        'runtime-php' => 'vm-site-runtime',
        'runtime-ruby' => 'vm-site-runtime',
        'runtime-static' => 'vm-site-runtime',
        'system-user' => 'vm-site-runtime',
        'laravel-stack' => 'vm-site-laravel',
        'rails-stack' => 'vm-site-rails',
        'wordpress' => 'vm-site-wordpress',
        'environment' => 'vm-site-environment',
        'logs' => 'vm-site-logs',
        'notifications' => 'vm-site-notifications',
        'basic-auth' => 'vm-site-authentication',
        'danger' => 'vm-site-danger',
        'cron' => 'vm-site-cron',
        'schedule' => 'vm-site-schedule',
        'daemons' => 'vm-site-daemons',
        'services' => 'vm-site-services',
        'backups' => 'vm-site-backups',
    ],

    'site_route_slugs' => [
        'sites.index' => 'vm-site-overview',
        'sites.create' => 'sites-and-deploy',
        'sites.create-custom' => 'sites-and-deploy',
        'sites.commits' => 'vm-site-repository',
        'sites.clone' => 'vm-site-overview',
        'sites.promote' => 'vm-site-overview',
        'sites.insights' => 'vm-site-monitor',
        'sites.env-diff' => 'vm-site-environment',
        'sites.webserver-config' => 'vm-site-webserver-config',
        'sites.caching' => 'vm-site-caching',
        'sites.cdn' => 'vm-site-cdn',
        'sites.monitor' => 'vm-site-monitor',
        'sites.cron' => 'vm-site-cron',
        'sites.daemons' => 'vm-site-daemons',
        'sites.services' => 'vm-site-services',
        'sites.queue-workers' => 'vm-site-daemons',
        'sites.workers' => 'vm-site-daemons',
        'sites.schedule' => 'vm-site-schedule',
        'sites.backups' => 'vm-site-backups',
        'sites.deployments.index' => 'vm-site-deploy',
        'sites.repository' => 'vm-site-repository',
        'sites.pipeline' => 'vm-site-deploy',
        'sites.routing' => 'vm-site-routing',
        'sites.errors' => 'vm-site-errors',
        'sites.resources' => 'vm-site-resources',
        'sites.files' => 'vm-site-files',
        'sites.source' => 'vm-site-repository',
    ],
];
