<?php

declare(strict_types=1);

namespace App\Services\Servers;

use App\Jobs\Concerns\PrivilegedRemoteFileWrites;
use App\Models\Server;
use App\Services\ConsoleActions\ConsoleEmitter;
use App\Services\SshConnection;
use App\Support\Servers\EnvoyAdminScript;
use App\Support\Servers\EnvoyConfigParser;

/**
 * Read + write operator-tunable fields in `/etc/envoy/envoy.yaml` that sit
 * outside dply's per-site routing blocks (admin bind, stat prefix, etc.).
 *
 * Site routing is regenerated by {@see EnvoyEdgeConfigBuilder}; custom
 * clusters are preserved via {@see EnvoyCustomClustersConfig} + server meta.
 */
class EnvoyStaticConfigOptions
{
    use PrivilegedRemoteFileWrites;

    private const REMOTE_PATH = '/etc/envoy/envoy.yaml';

    /**
     * @var array<string, array{type: string, default: string, label: string, help: string, group: string}>
     */
    public const PARAMS = [
        'admin_port' => [
            'type' => 'string',
            'default' => '9901',
            'group' => 'admin',
            'label' => 'Admin port',
            'help' => 'Localhost admin interface port (127.0.0.1). dply probes and the in-app admin link use this port.',
        ],
        'stat_prefix' => [
            'type' => 'string',
            'default' => 'dply_ingress',
            'group' => 'listener',
            'label' => 'HTTP stat prefix',
            'help' => 'Prefix for ingress stats on the primary HTTP connection manager.',
        ],
    ];

    /**
     * @var array<string, string>
     */
    public const PARAM_GROUPS = [
        'admin' => 'Admin interface',
        'listener' => 'Primary listener',
    ];

    /**
     * Install Envoy binary + systemd unit (shared with {@see AddEdgeProxyJob}).
     */
    public static function installScript(): string
    {
        return <<<'BASH'
set -euo pipefail
DPLY_ARCH=$(uname -m)
case "$DPLY_ARCH" in
  x86_64|amd64) DPLY_ARCH=x86_64 ;;
  aarch64|arm64) DPLY_ARCH=aarch_64 ;;
  *) echo "[dply] unsupported arch: $DPLY_ARCH" >&2; exit 127 ;;
esac

if [ -x /usr/local/bin/envoy ] && [ -f /etc/systemd/system/envoy.service ]; then
  echo "[dply] envoy already installed; skipping."
else
  apt-get install -y --no-install-recommends curl ca-certificates
  ENVOY_VERSION="${ENVOY_VERSION:-1.32.6}"
  ENVOY_URL="https://github.com/envoyproxy/envoy/releases/download/v${ENVOY_VERSION}/envoy-${ENVOY_VERSION}-linux-${DPLY_ARCH}"
  echo "[dply] downloading envoy ${ENVOY_VERSION} (linux/${DPLY_ARCH})…"
  curl -fSL "$ENVOY_URL" -o /tmp/envoy.bin
  install -m 0755 /tmp/envoy.bin /usr/local/bin/envoy
  rm -f /tmp/envoy.bin
  echo "[dply] envoy installed at /usr/local/bin/envoy"
fi
mkdir -p /etc/envoy
cat > /etc/systemd/system/envoy.service <<'UNIT'
[Unit]
Description=Envoy Proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/envoy -c /etc/envoy/envoy.yaml
Restart=on-failure
RestartSec=10s
StartLimitIntervalSec=120
StartLimitBurst=5
TimeoutStartSec=120
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
[ -x /usr/local/bin/envoy ] || { echo "[dply] envoy binary missing at /usr/local/bin/envoy" >&2; exit 127; }
[ -f /etc/systemd/system/envoy.service ] || { echo "[dply] envoy.service file missing" >&2; exit 127; }
systemctl cat envoy.service >/dev/null 2>&1 || { echo "[dply] envoy.service not picked up by systemd" >&2; exit 127; }
BASH;
    }

    /**
     * @return array{values: array<string, string>, unreadable: bool}
     */
    /** @return array<string, mixed> */
    public function read(Server $server): array
    {
        $contents = $this->readRemote($server);
        if ($contents === null) {
            return ['values' => self::defaultForm(), 'unreadable' => true];
        }

        $settings = EnvoyConfigParser::operatorSettings($contents);
        $values = self::defaultForm();
        foreach (self::PARAMS as $key => $meta) {
            if (array_key_exists($key, $settings)) {
                $values[$key] = (string) $settings[$key];
            } elseif ($meta['default'] !== '') {
                $values[$key] = $meta['default'];
            }
        }

        return ['values' => $values, 'unreadable' => false];
    }

    /**
     * @param  array<string, mixed> $form
     */
    public function save(Server $server, array $form, ?ConsoleEmitter $emitter = null): void
    {
        $emit = $emitter ?? new ConsoleEmitter(null);
        $contents = $this->readRemote($server);
        if ($contents === null) {
            throw new \RuntimeException('Could not read envoy.yaml from the server.');
        }

        $port = (int) ($form['admin_port'] ?? 9901);
        if ($port < 1 || $port > 65535) {
            throw new \RuntimeException('Admin port must be between 1 and 65535.');
        }

        $settings = [
            'admin_port' => (string) $port,
            'stat_prefix' => trim((string) ($form['stat_prefix'] ?? 'dply_ingress')) ?: 'dply_ingress',
        ];

        $meta = is_array($server->meta) ? $server->meta : [];
        $meta['envoy_operator_settings'] = $settings;
        $server->forceFill(['meta' => $meta])->save();

        $merged = EnvoyConfigParser::mergeOperatorSettings($contents, $settings);
        $this->stageValidateRestart($server, $emit, $merged, 'update operator settings');
        $emit->success('Envoy restarted with updated static settings.');
    }

    public function repairAdminDefaults(Server $server, ?ConsoleEmitter $emitter = null): void
    {
        $emit = $emitter ?? new ConsoleEmitter(null);
        $contents = $this->readRemote($server);
        if ($contents === null) {
            throw new \RuntimeException('Could not read envoy.yaml from the server.');
        }

        $settings = EnvoyConfigParser::defaultOperatorSettings();
        $meta = is_array($server->meta) ? $server->meta : [];
        $meta['envoy_operator_settings'] = $settings;
        $server->forceFill(['meta' => $meta])->save();

        $merged = EnvoyConfigParser::mergeOperatorSettings($contents, $settings);
        $this->stageValidateRestart($server, $emit, $merged, 'repair admin defaults');
        $emit->success('Envoy admin defaults restored on 127.0.0.1:9901.');
    }

    public function startEnvoyService(Server $server, ?ConsoleEmitter $emitter = null): void
    {
        $emit = $emitter ?? new ConsoleEmitter(null);
        $ssh = new SshConnection($server);
        $output = $ssh->exec($this->privilegedCommand($server, EnvoyAdminScript::startServiceScript()), 120);
        $exit = $ssh->lastExecExitCode() ?? 1;
        if ($exit !== 0) {
            $emit->error(trim((string) $output));
            throw new \RuntimeException(trim((string) $output) !== '' ? trim((string) $output) : 'Failed to start Envoy.');
        }
        $emit->info(trim((string) $output));
        $emit->success('Envoy is running.');
    }

    /**
     * @return array<string, string>
     */
    public static function operatorSettingsFromServer(Server $server): array
    {
        $meta = is_array($server->meta) ? $server->meta : [];
        $stored = $meta['envoy_operator_settings'] ?? null;

        if (is_array($stored)) {
            return array_merge(EnvoyConfigParser::defaultOperatorSettings(), $stored);
        }

        return EnvoyConfigParser::defaultOperatorSettings();
    }

    /**
     * @return array<string, string>
     */
    private static function defaultForm(): array
    {
        $out = [];
        foreach (self::PARAMS as $key => $meta) {
            $out[$key] = $meta['default'];
        }

        return $out;
    }

    private function readRemote(Server $server): ?string
    {
        try {
            $ssh = new SshConnection($server);
            $contents = $ssh->exec($this->privilegedCommand($server, 'cat '.escapeshellarg(self::REMOTE_PATH).' 2>/dev/null'), 15);
            if ($contents === '' || ($ssh->lastExecExitCode() ?? 1) !== 0) {
                return null;
            }

            return (string) $contents;
        } catch (\Throwable) {
            return null;
        }
    }

    private function stageValidateRestart(Server $server, ConsoleEmitter $emit, string $contents, string $reason): void
    {
        $ssh = new SshConnection($server);
        $backup = self::REMOTE_PATH.'.dply-bak-'.time();
        $emit->step('envoy-static', 'Snapshot current envoy.yaml');
        $ssh->exec($this->privilegedCommand($server, sprintf(
            'cp %s %s',
            escapeshellarg(self::REMOTE_PATH),
            escapeshellarg($backup),
        )), 15);

        $tmp = '/tmp/dply-envoy-'.bin2hex(random_bytes(6)).'.yaml';
        $this->writeRemoteFile($server, $ssh, $tmp, $contents);
        $emit->step('envoy-static', 'Validate '.$reason);
        $validate = $ssh->exec($this->privilegedCommand($server, sprintf(
            'envoy --mode validate -c %s 2>&1 || /usr/local/bin/envoy --mode validate -c %s 2>&1',
            escapeshellarg($tmp),
            escapeshellarg($tmp),
        )), 60);
        if (($ssh->lastExecExitCode() ?? 1) !== 0) {
            $ssh->exec($this->privilegedCommand($server, 'rm -f '.escapeshellarg($tmp)), 10);
            $emit->error(trim((string) $validate));
            throw new \RuntimeException(trim((string) $validate) !== '' ? trim((string) $validate) : 'Envoy config validation failed.');
        }

        $emit->step('envoy-static', 'Install updated envoy.yaml');
        $ssh->exec($this->privilegedCommand($server, sprintf(
            'install -m 0644 %s %s && rm -f %s',
            escapeshellarg($tmp),
            escapeshellarg(self::REMOTE_PATH),
            escapeshellarg($tmp),
        )), 30);

        $emit->step('envoy-static', 'Restart envoy.service');
        $restart = $ssh->exec($this->privilegedCommand($server, EnvoyAdminScript::startServiceScript()), 120);
        if (($ssh->lastExecExitCode() ?? 1) !== 0) {
            $ssh->exec($this->privilegedCommand($server, sprintf(
                'cp %s %s',
                escapeshellarg($backup),
                escapeshellarg(self::REMOTE_PATH),
            )), 15);
            $ssh->exec($this->privilegedCommand($server, 'systemctl restart envoy 2>&1 || true'), 60);
            $emit->error(trim((string) $restart));
            throw new \RuntimeException(trim((string) $restart) !== '' ? trim((string) $restart) : 'Envoy failed to restart after config change.');
        }
        $emit->info(trim((string) $restart));
    }

    private function writeRemoteFile(Server $server, SshConnection $ssh, string $path, string $contents): void
    {
        $encoded = base64_encode($contents);
        $script = sprintf(
            "printf '%%s' %s | base64 -d > %s && chmod 0644 %s",
            escapeshellarg($encoded),
            escapeshellarg($path),
            escapeshellarg($path),
        );
        $ssh->exec($this->privilegedCommand($server, $script), 30);
        if (($ssh->lastExecExitCode() ?? 1) !== 0) {
            throw new \RuntimeException('Could not write temporary envoy.yaml on the server.');
        }
    }
}
