<?php

namespace App\Services\Servers;

use App\Models\Server;

/**
 * Generates a Terraform-flavored snippet for documentation / hand-off (not applied automatically).
 */
class FirewallTerraformExporter
{
    public function toHcl(Server $server): string
    {
        $server->load(['firewallRules' => fn ($q) => $q->orderBy('sort_order')]);
        $name = preg_replace('/[^a-zA-Z0-9_]/', '_', $server->name) ?: 'server';
        $lines = [
            '# Generated by '.config('app.name').' — review before use. UFW remains source of truth on the host.',
            '# Digital Ocean example (adjust droplet id / tags):',
            'resource "digitalocean_firewall" "dply_'.$name.'" {',
            '  name = "dply-'.addslashes($server->name).'"',
            '',
            '  droplet_ids = [] # set your droplet id(s)',
            '',
        ];

        foreach ($server->firewallRules->where('enabled', true) as $r) {
            $proto = $r->protocol;
            if (in_array($proto, ['icmp', 'ipv6-icmp'], true)) {
                $lines[] = '  # ICMP rule — map manually in cloud SG (no port): '.addslashes((string) $r->name);

                continue;
            }
            if ($r->port === null) {
                continue;
            }
            $lines[] = sprintf(
                '  inbound_rule { protocol = "%s" port_range = "%s" source_addresses = ["0.0.0.0/0", "::/0"] } # %s',
                addslashes((string) $proto),
                (int) $r->port,
                addslashes((string) ($r->name ?? ''))
            );
        }

        $lines[] = '}';

        return implode("\n", $lines)."\n";
    }
}
