<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\AuditLog;
use App\Models\EdgeSiteAccessRule;
use App\Models\Organization;
use App\Models\Server;
use App\Models\Site;
use App\Models\SiteCertificate;
use App\Models\SiteDeployment;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use ZipArchive;

/**
 * One-click org compliance export. Bundles the audit log, deploy
 * history, certificate status, and Edge access rules into a single ZIP
 * that auditors can drop into a ticket. Mirrors the SOC2-style "show
 * me what happened in your platform in the last 90 days" question.
 *
 * Gated to org admins, same as the on-screen Activity page. The ZIP
 * is written to a tempfile and served via Laravel's deleteFileAfterSend
 * so we don't leave artefacts on disk.
 */
class OrganizationComplianceExportController extends Controller
{
    public function __invoke(Organization $organization): BinaryFileResponse
    {
        $this->authorize('view', $organization);
        abort_unless($organization->hasAdminAccess(auth()->user()), 403);

        $tempPath = tempnam(sys_get_temp_dir(), 'dply-compliance-');
        if ($tempPath === false) {
            abort(500, 'Could not allocate temp file for compliance export.');
        }

        $zip = new ZipArchive;
        if ($zip->open($tempPath, ZipArchive::OVERWRITE) !== true) {
            abort(500, 'Could not open ZIP for writing.');
        }

        $zip->addFromString('README.txt', $this->readme($organization));
        $zip->addFromString('audit_log.csv', $this->auditLogCsv($organization));
        $zip->addFromString('deploys.csv', $this->deployHistoryCsv($organization));
        $zip->addFromString('certificates.csv', $this->certificatesCsv($organization));
        $zip->addFromString('edge_access_rules.csv', $this->edgeAccessRulesCsv($organization));
        $zip->close();

        $stem = preg_replace('/[^a-z0-9-]+/i', '-', (string) $organization->name) ?: 'org';
        $filename = sprintf('dply-compliance-%s-%s.zip', $stem, now()->format('Ymd-His'));

        return response()->download($tempPath, $filename, [
            'Content-Type' => 'application/zip',
            'Cache-Control' => 'no-store, max-age=0',
        ])->deleteFileAfterSend(true);
    }

    private function readme(Organization $organization): string
    {
        $generatedAt = now()->toIso8601String();

        return implode("\n", [
            'dply compliance export',
            '======================',
            '',
            'Organization: '.$organization->name.' ('.$organization->id.')',
            'Generated at: '.$generatedAt,
            'Generated by: '.(auth()->user()?->email ?? 'unknown'),
            '',
            'Files in this archive:',
            '  audit_log.csv         — every audited event for this organization (full history).',
            '  deploys.csv           — site deployment history across BYO + Cloud + Serverless surfaces.',
            '  certificates.csv      — TLS certificate inventory with expiry dates.',
            '  edge_access_rules.csv — Edge preview-protection rules per site.',
            '',
            'Timestamps are ISO 8601 UTC. JSON-valued columns are rendered as compact JSON.',
            'Sensitive material (passwords, secrets, raw key material) is intentionally excluded.',
            '',
        ]);
    }

    private function auditLogCsv(Organization $organization): string
    {
        $query = AuditLog::query()
            ->where('organization_id', $organization->id)
            ->with('user:id,name,email')
            ->orderBy('created_at');

        return $this->streamCsv(
            ['occurred_at', 'actor_name', 'actor_email', 'action', 'subject_type', 'subject_id', 'old_values_json', 'new_values_json', 'ip_address'],
            $query,
            fn (AuditLog $row) => [
                $row->created_at?->toIso8601String() ?? '',
                (string) ($row->user?->name ?? ''),
                (string) ($row->user?->email ?? ''),
                (string) $row->action,
                (string) ($row->subject_type ?? ''),
                (string) ($row->subject_id ?? ''),
                $row->old_values === null ? '' : json_encode($row->old_values, JSON_UNESCAPED_SLASHES),
                $row->new_values === null ? '' : json_encode($row->new_values, JSON_UNESCAPED_SLASHES),
                (string) ($row->ip_address ?? ''),
            ],
        );
    }

    private function deployHistoryCsv(Organization $organization): string
    {
        $siteIdQuery = Site::query()
            ->where('organization_id', $organization->id)
            ->orWhereIn('server_id', Server::query()->where('organization_id', $organization->id)->select('id'));

        $query = SiteDeployment::query()
            ->with('site:id,name,server_id')
            ->whereIn('site_id', $siteIdQuery->select('id'))
            ->orderBy('started_at');

        return $this->streamCsv(
            ['started_at', 'finished_at', 'site', 'site_id', 'status', 'trigger', 'git_sha', 'exit_code', 'duration_seconds'],
            $query,
            function (SiteDeployment $row) {
                $duration = $row->started_at && $row->finished_at
                    ? (int) round($row->finished_at->getTimestamp() - $row->started_at->getTimestamp())
                    : '';

                return [
                    $row->started_at?->toIso8601String() ?? '',
                    $row->finished_at?->toIso8601String() ?? '',
                    (string) ($row->site?->name ?? ''),
                    (string) $row->site_id,
                    (string) $row->status,
                    (string) ($row->trigger ?? ''),
                    (string) ($row->git_sha ?? ''),
                    $row->exit_code === null ? '' : (string) $row->exit_code,
                    (string) $duration,
                ];
            },
        );
    }

    private function certificatesCsv(Organization $organization): string
    {
        $siteIdQuery = Site::query()
            ->where('organization_id', $organization->id)
            ->orWhereIn('server_id', Server::query()->where('organization_id', $organization->id)->select('id'));

        $query = SiteCertificate::query()
            ->with('site:id,name')
            ->whereIn('site_id', $siteIdQuery->select('id'))
            ->orderBy('expires_at');

        return $this->streamCsv(
            ['site', 'site_id', 'certificate_id', 'provider_type', 'challenge_type', 'scope_type', 'status', 'domains_json', 'expires_at', 'last_requested_at', 'last_installed_at'],
            $query,
            fn (SiteCertificate $row) => [
                (string) ($row->site?->name ?? ''),
                (string) $row->site_id,
                (string) $row->id,
                (string) ($row->provider_type ?? ''),
                (string) ($row->challenge_type ?? ''),
                (string) ($row->scope_type ?? ''),
                (string) $row->status,
                $row->domains_json === null ? '' : (is_string($row->domains_json) ? $row->domains_json : json_encode($row->domains_json, JSON_UNESCAPED_SLASHES)),
                $row->expires_at?->toIso8601String() ?? '',
                $row->last_requested_at?->toIso8601String() ?? '',
                $row->last_installed_at?->toIso8601String() ?? '',
            ],
        );
    }

    private function edgeAccessRulesCsv(Organization $organization): string
    {
        $siteIdQuery = Site::query()
            ->where('organization_id', $organization->id)
            ->orWhereIn('server_id', Server::query()->where('organization_id', $organization->id)->select('id'));

        $query = EdgeSiteAccessRule::query()
            ->with('site:id,name')
            ->whereIn('site_id', $siteIdQuery->select('id'))
            ->orderBy('created_at');

        return $this->streamCsv(
            ['site', 'site_id', 'mode', 'allowed_emails_json', 'created_at', 'updated_at'],
            $query,
            fn (EdgeSiteAccessRule $row) => [
                (string) ($row->site?->name ?? ''),
                (string) $row->site_id,
                (string) $row->mode,
                $row->allowed_emails === null ? '' : json_encode($row->allowed_emails, JSON_UNESCAPED_SLASHES),
                $row->created_at?->toIso8601String() ?? '',
                $row->updated_at?->toIso8601String() ?? '',
            ],
        );
    }

    /**
     * Buffered CSV writer — used for the ZIP entries where the whole
     * file has to be in memory before zip->addFromString. Chunked reads
     * keep peak memory bounded even on large orgs.
     *
     * @param  list<string>  $header
     * @param  Builder<*>  $query
     * @param  callable(Model): list<string|int>  $mapper
     */
    private function streamCsv(array $header, Builder $query, callable $mapper): string
    {
        $buffer = fopen('php://temp', 'w+b');
        if ($buffer === false) {
            return '';
        }
        fputcsv($buffer, $header, ',', '"', '');
        $query->chunkById(500, function ($chunk) use ($buffer, $mapper): void {
            foreach ($chunk as $row) {
                fputcsv($buffer, $mapper($row), ',', '"', '');
            }
        });
        rewind($buffer);
        $contents = stream_get_contents($buffer);
        fclose($buffer);

        return $contents === false ? '' : $contents;
    }
}
