<?php

declare(strict_types=1);

namespace Tests\Unit;

use App\Models\Server;
use App\Models\Site;
use App\Models\SiteProcess;
use App\Services\Sites\SiteManifestExporter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Symfony\Component\Yaml\Yaml;
use Tests\TestCase;

class SiteManifestExporterTest extends TestCase
{
    use RefreshDatabase;

    public function test_exports_runtime_version_build_release(): void
    {
        $server = Server::factory()->create();
        $site = Site::factory()->create([
            'server_id' => $server->id,
            'runtime' => 'node',
            'runtime_version' => '20.10.0',
            'build_command' => 'npm run build',
            'start_command' => 'node server.js',
        ]);

        $rendered = (new SiteManifestExporter)->render($site);
        $parsed = Yaml::parse($rendered);

        $this->assertSame('node', $parsed['runtime']);
        $this->assertSame('20.10.0', $parsed['version']);
        $this->assertSame(['npm run build'], $parsed['build']);
        $this->assertSame(['node server.js'], $parsed['release']);
    }

    public function test_exports_processes_with_scale_when_not_one(): void
    {
        $server = Server::factory()->create();
        $site = Site::factory()->create([
            'server_id' => $server->id,
            'runtime' => 'php',
        ]);
        // Site::created hook auto-creates a 'web' process at scale=1.
        SiteProcess::factory()->create([
            'site_id' => $site->id,
            'type' => SiteProcess::TYPE_WORKER,
            'name' => 'queue',
            'command' => 'php artisan queue:work',
            'scale' => 3,
            'is_active' => true,
        ]);

        $parsed = Yaml::parse((new SiteManifestExporter)->render($site));

        $this->assertArrayHasKey('queue', $parsed['processes']);
        $this->assertSame('php artisan queue:work', $parsed['processes']['queue']['command']);
        $this->assertSame(3, $parsed['processes']['queue']['scale']);
        // Web is scale=1 so the scale key is omitted.
        $this->assertArrayNotHasKey('scale', $parsed['processes']['web']);
    }

    public function test_omits_empty_fields(): void
    {
        $server = Server::factory()->create();
        $site = Site::factory()->create([
            'server_id' => $server->id,
            'runtime' => 'static',
            'runtime_version' => null,
            'build_command' => null,
            'start_command' => null,
        ]);
        // Remove auto-created web process so the output is truly minimal.
        $site->processes()->delete();

        $rendered = (new SiteManifestExporter)->render($site);
        $parsed = Yaml::parse($rendered);

        $this->assertSame(['runtime' => 'static'], $parsed);
    }

    public function test_rendered_manifest_starts_with_provenance_header(): void
    {
        $server = Server::factory()->create();
        $site = Site::factory()->create([
            'server_id' => $server->id,
            'runtime' => 'php',
        ]);

        $rendered = (new SiteManifestExporter)->render($site);

        $this->assertStringStartsWith('# Generated by dply:site:export-manifest', $rendered);
        $this->assertStringContainsString($site->id, $rendered);
    }
}
